server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallet/**
          filters:
            - StripPrefix=1

    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 4E57682B4D6251655468576D5A7134743777217A25432A462D4A614E64526755
