server:
  port: 8080

spring:
  application:
    name: api-gateway

cloud:
  gateway:
    routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
          - Path=/api/auth/**
      - id: wallet-service
        uri: lb://wallet-service
        predicates:
          - Path=/api/wallet/**
jwt:
  secret: 4E57682B4D6251655468576D5A7134743777217A25432A462D4A614E64526755
