server:
  port: 8081

spring:
  application:
    name: auth-service 

  config:
    import: optional:configserver:http://localhost:8888		

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 4E57682B4D6251655468576D5A7134743777217A25432A462D4A614E64526755
  expiration: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG
